apiVersion: v1
kind: Service
metadata:
  name: {{ include "dods.fullname" . }}
  labels:
    {{- include "dods.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: rcon
      targetPort: rcon
      protocol: TCP
      port: {{ .Values.service.ports.rcon }}
    - name: gameplay
      targetPort: gameplay
      protocol: UDP
      port: {{ .Values.service.ports.gameplay }}
  selector:
    {{- include "dods.selectorLabels" . | nindent 4 }}
