apiVersion: v1
kind: Service
metadata:
  name: {{ include "dods.fullname" . }}
  labels:
    {{- include "dods.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: rcon
      targetPort: rcon
      protocol: TCP
      port: {{ .Values.ports.rcon }}
    - name: gameplay
      targetPort: gameplay
      protocol: UDP
      port: {{ .Values.ports.gameplay }}
  selector:
    {{- include "dods.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dods.fullname" . }}-external
  labels:
    {{- include "dods.labels" . | nindent 4 }}
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: rcon
      protocol: TCP
      port: {{ .Values.ports.rcon }}
    - name: gameplay
      protocol: UDP
      port: {{ .Values.ports.gameplay }}
  selector:
    {{- include "dods.selectorLabels" . | nindent 4 }}
