apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dods.fullname" . }}
  labels:
    {{- include "dods.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "dods.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "dods.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "dods.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          args:
            - "+port"
            - "{{ .Values.ports.gameplay }}"
            - "+rcon_port"
            - "{{ .Values.ports.rcon }}"
            - "+hostname"
            - "{{ .Values.config.hostname }}"
            - "+map"
            - "{{ .Values.config.map }}"
            - "+maxplayers"
            - "{{ .Values.config.maxplayers }}"
            - "+rcon_password"
            - "{{ .Values.config.rcon_password }}"
          ports:
            - name: rcon
              containerPort: {{ .Values.ports.rcon }}
              protocol: TCP
            - name: gameplay
              containerPort: {{ .Values.ports.gameplay }}
              protocol: UDP
